name: Deploy

on:
  push:
    branches:
      - main
      - HerokuHotfix
      - HerokuHotfix2
      - HerokuHotfix3
      - Releases
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "zrsquared" #Must be unique in Heroku
          heroku_email: "fxc1158@aut.ac.nz"
          appdir: "frontend" # we only want to serve the frontend for now...

